// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1TGEdICarJcPLisuu0fk-895LLtw6wAw',
    appId: '1:316360646191:web:cc2edccdc10ee43cb1f0da',
    messagingSenderId: '316360646191',
    projectId: 'flex-studentapp',
    authDomain: 'flex-studentapp.firebaseapp.com',
    storageBucket: 'flex-studentapp.appspot.com',
    measurementId: 'G-T6WP0ENL28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQdJdTFWTIV10IkwzHJ6j-baQgyyZ0PEY',
    appId: '1:316360646191:android:78c6d2e628ef0bf0b1f0da',
    messagingSenderId: '316360646191',
    projectId: 'flex-studentapp',
    storageBucket: 'flex-studentapp.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1TGEdICarJcPLisuu0fk-895LLtw6wAw',
    appId: '1:316360646191:web:85eb925e05f255a0b1f0da',
    messagingSenderId: '316360646191',
    projectId: 'flex-studentapp',
    authDomain: 'flex-studentapp.firebaseapp.com',
    storageBucket: 'flex-studentapp.appspot.com',
    measurementId: 'G-NXS0363MQG',
  );
}
